version: "3"
services:


  client:
    container_name: social-frontend
    image: index.docker.io/prashrex/social-frontend
    restart: always
    build: 
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    
    